export const RAW_REPORT_ROW_HEIGHT_PX = 58;
export const REPORT_COPY_STATE_DURATION_MS = 1200;
export const REPORT_LIST_OVERSCAN_COUNT = 8;
export const REPORT_TREE_BAR_MAX_WIDTH_PERCENT = 100;
export const REPORT_TREE_BAR_MIN_WIDTH_PERCENT = 3;
export const REPORT_TREE_INDENT_PX = 14;
export const REPORT_TREE_MIN_WIDTH_PX = 520;
