export const DEFAULT_REPORT_LIMIT = 100;
export const DEFAULT_RAW_REPORT_MAX_RECORDS = 10_000;
export const REPORT_VALUE_MAX_DEPTH = 2;
export const REPORT_VALUE_MAX_ENTRIES = 20;
export const REPORT_VALUE_MAX_STRING_LENGTH = 200;
export const REPORT_REASON_MAX_EXAMPLES = 3;
